name: Check IMAX

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: python check.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CHAT_ID_FRUBI: ${{ secrets.CHAT_ID_FRUBI }}

      - name: Save state
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add state.json
          git commit -m "Update state" || exit 0
          git push
